#!/usr/bin/env python
import os
import sys
import time
import argparse
import platform

sys.path.insert(1, os.path.join(sys.path[0], '..'))
from src.rbm_models.run_rbm import Runner

start = time.time()
runner = Runner()
runner.run()
delta = (time.time() - start)
print('Elapsed time = {:.4f} secs ({:.4f} mins)'.format(delta, delta/60.0))
